payload_status: 1
gripper_type: 5.0
payload_mass: 1.4
safety_type: 1.0

payload_com:
  x: 0.0
  y: 0.0
  z: -0.14

payload_moi:
  Ixx: 0.00001
  Iyy: 0.00001
  Izz: 0.00001 
  Ixy: 0.0
  Ixz: 0.0
  Iyz: 0.0

ft_type: 0.0

ft_rot:
  R1: [1.0, 0.0, 0.0]
  R2: [0.0, 1.0, 0.0]
  R3: [0.0, 0.0, 1.0]
