controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

velocity_controller:
  ros__parameters:
    type: addverb_cobot_controllers/VelocityController  
    # joints:
    #   - joint1
    #   - joint2
    #   - joint3
    #   - joint4
    #   - joint5
    #   - joint6
  #  interface_name: velocity
    # type: addverb_cobot_controllers/VelocityController
    commands:
      - joint1/velocity
      - joint2/velocity
      - joint3/velocity
      - joint4/velocity
      - joint5/velocity
      - joint6/velocity
      # - controller_name/velocity
    states:
      - robot_state/state    
      
ptp_joint_controller:
  ros__parameters:
    type: addverb_cobot_controllers/PTPJointController
    commands:
      - joint1/position
      - joint2/position
      - joint3/position
      - joint4/position
      - joint5/position
      - joint6/position
      - time_cmd/time
      - ptp_transfer/cmd
      - controller_name/ptp_joint
    states:
      - joint1/position
      - joint2/position
      - joint3/position
      - joint4/position
      - joint5/position
      - joint6/position
      - ptp_transfer/state
      - robot_state/state

free_drive_controller:
  ros__parameters:
    type: addverb_cobot_controllers/FreeDriveController
    states:
      - joint1/position
      - joint2/position
      - joint3/position
      - joint4/position
      - joint5/position
      - joint6/position
      - robot_state/state
    commands:
      - controller_name/free_drive


ptp_tcp_controller:
  ros__parameters:
    type: addverb_cobot_controllers/PTPTCPController
    commands:
      - tcp/x
      - tcp/y
      - tcp/z
      - tcp/r
      - tcp/p
      - tcp/yaw
      - tcp_time_cmd/time
      - ptp_tcp_transfer/cmd
      - controller_name/ptp_tcp
    states:
      - tcp/x
      - tcp/y
      - tcp/z
      - tcp/r
      - tcp/p
      - tcp/yaw
      - ptp_tcp_transfer/state
      - robot_state/state

recorder_controller:
  ros__parameters:
    type: addverb_cobot_controllers/RecorderController
    commands:
        - joint1/position
        - joint2/position
        - joint3/position
        - joint4/position
        - joint5/position
        - joint6/position
        - time_cmd/time
        - ptp_transfer/cmd
        - record_cmd/iterations
        - controller_name/recorder

    states:
        - joint1/position
        - joint2/position
        - joint3/position
        - joint4/position
        - joint5/position
        - joint6/position
        - ptp_transfer/state
        - robot_state/state

    max_recording_rate: 30
    position_tolerance: 0.001
    time_tolerance: 15.0


      
joint_jogging_controller:
  ros__parameters:
    type: addverb_cobot_controllers/JointJoggingController
    commands:
      - joint_jogging/joint_1
      - joint_jogging/joint_2
      - joint_jogging/joint_3
      - joint_jogging/joint_4
      - joint_jogging/joint_5
      - joint_jogging/joint_6
      - controller_name/joint_jogging
    states:
      - robot_state/state    

cartesian_jogging_controller:
  ros__parameters:
    type: addverb_cobot_controllers/CartesianJoggingController
    commands:
      - cartesian_jogging/linear_x
      - cartesian_jogging/linear_y
      - cartesian_jogging/linear_z
      - cartesian_jogging/angular_x
      - cartesian_jogging/angular_y
      - cartesian_jogging/angular_z
      - controller_name/cartesian_jogging
    states:
      - robot_state/state

joint_impedance_controller:
  ros__parameters:
    type: addverb_cobot_controllers/JointImpedanceController
    commands:
      - joint1/position
      - joint2/position
      - joint3/position
      - joint4/position
      - joint5/position
      - joint6/position
      - joint_impedance/stiffness_j1
      - joint_impedance/stiffness_j2
      - joint_impedance/stiffness_j3
      - joint_impedance/stiffness_j4
      - joint_impedance/stiffness_j5
      - joint_impedance/stiffness_j6
      - joint_impedance/damping_j1
      - joint_impedance/damping_j2
      - joint_impedance/damping_j3
      - joint_impedance/damping_j4
      - joint_impedance/damping_j5
      - joint_impedance/damping_j6
      - time_cmd/time
      - ptp_transfer/cmd
      - controller_name/joint_impedance
    states:
      - joint1/position
      - joint2/position
      - joint3/position
      - joint4/position
      - joint5/position
      - joint6/position
      - ptp_transfer/state
      - robot_state/state

cartesian_impedance_controller:
  ros__parameters:
    type: addverb_cobot_controllers/CartesianImpedanceController
    commands:
      - joint1/position
      - joint2/position
      - joint3/position
      - joint4/position
      - joint5/position
      - joint6/position
      - cartesian_impedance/stiffness_j1
      - cartesian_impedance/stiffness_j2
      - cartesian_impedance/stiffness_j3
      - cartesian_impedance/stiffness_j4
      - cartesian_impedance/stiffness_j5
      - cartesian_impedance/stiffness_j6
      - cartesian_impedance/damping_j1
      - cartesian_impedance/damping_j2
      - cartesian_impedance/damping_j3
      - cartesian_impedance/damping_j4
      - cartesian_impedance/damping_j5
      - cartesian_impedance/damping_j6
      - cartesian_impedance/mass_matrix_r11
      - cartesian_impedance/mass_matrix_r22
      - cartesian_impedance/mass_matrix_r33
      - cartesian_impedance/mass_matrix_r44
      - cartesian_impedance/mass_matrix_r55
      - cartesian_impedance/mass_matrix_r66
      - cartesian_impedance/ft_force_x
      - cartesian_impedance/ft_force_y
      - cartesian_impedance/ft_force_z
      - cartesian_impedance/ft_torque_x
      - cartesian_impedance/ft_torque_y
      - cartesian_impedance/ft_torque_z
      - cartesian_impedance/target_force_x
      - cartesian_impedance/target_force_y
      - cartesian_impedance/target_force_z
      - cartesian_impedance/target_torque_x
      - cartesian_impedance/target_torque_y
      - cartesian_impedance/target_torque_z
      - time_cmd/time
      - ptp_transfer/cmd
      - controller_name/cartesian_impedance
    states:
      - joint1/position
      - joint2/position
      - joint3/position
      - joint4/position
      - joint5/position
      - joint6/position
      - ptp_transfer/state
      - robot_state/state

gravity_comp_effort_controller:
  ros__parameters:
    type: addverb_cobot_controllers/GravityCompEffortController
    commands:
      - joint1/effort
      - joint2/effort
      - joint3/effort
      - joint4/effort
      - joint5/effort
      - joint6/effort
      - controller_name/gravity_comp_effort
    states:
      - robot_state/state

effort_controller:
  ros__parameters:
    type: addverb_cobot_controllers/EffortController
    commands:
      - joint1/effort
      - joint2/effort
      - joint3/effort
      - joint4/effort
      - joint5/effort
      - joint6/effort
    states:
      - robot_state/state

gripper_controller:
  ros__parameters:
    type: addverb_cobot_controllers/GripperController
    commands:
      - gripper/transfer_cmd
      - gripper/position
      - gripper/grasp_force