controller_manager:
  ros__parameters:
    update_rate: 100

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    #velocity_controller:
      #type: forward_command_controller/ForwardCommandController

    gripper_controller:
      type: position_controllers/GripperActionController
      #type: joint_trajectory_controller/JointTrajectoryController
   
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


arm_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    open_loop_control: true
    allow_integration_in_goal_trajectories: true

    allow_nonzero_velocity_at_trajectory_end: true
    constraints:
      goal_time: 0.0
    allow_partial_joints_goal: true

#velocity_controller:
#  ros__parameters:
#    joints:
#      - joint1
#      - joint2
#      - joint3
#      - joint4
#      - joint5
#      - joint6
#    interface_name: velocity

gripper_controller:
  ros__parameters:
    joint: finger_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

#gripper_controller:
#  ros__parameters:
#    type: joint_trajectory_controller/JointTrajectoryController
#    joints: 
#      - finger_joint
#    command_interfaces:
#      - position
#    state_interfaces:
#      - position
    
#    open_loop_control: true
#    allow_integration_in_goal_trajectories: true